server:
  port: 8080
  servlet:
    context-path: /wealth-ledger

spring:
  application:
    name: wealth-ledger

  flyway:
    enabled: true
    locations: classpath:db/migration
    default-schema: ledger
    schemas: ledger
    create-schemas: true

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/wealth_ledger}
    username: ${DB_USERNAME:hgiai456}
    password: ${DB_PASSWORD:Dhg3012.}
    driver-class-name: org.postgresql.Driver

    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      connection-timeout: 30000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

app:
  bootstrap-admin:
    enabled: false

jwt:
  signerKey: ${JWT_SIGNER_KEY:1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij}
  valid-duration: 3600
  refreshable-duration: 360000